## Estimation of Hedge Ratio

In [42]:
import numpy as np
import pandas as pd
import yfinance as yf
import statsmodels.formula.api as smf

In [43]:
df = yf.download("^GSPC", start="2000-1-1")
df_futures = yf.download("ES=F", start="2001-1-1")

df.columns = df.columns.get_level_values(0)
df_futures.columns = df_features.columns.get_level_values(0)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [44]:
df.head()

Price             Close         High          Low         Open      Volume
Date
2000-01-03  1455.219971  1478.000000  1438.359985  1469.250000   931800000
2000-01-04  1399.420044  1455.219971  1397.430054  1455.219971  1009000000
2000-01-05  1402.109985  1413.270020  1377.680054  1399.420044  1085500000
2000-01-06  1403.449951  1411.900024  1392.099976  1402.109985  1092300000
2000-01-07  1441.469971  1441.469971  1400.729980  1403.449951  1225200000

In [45]:
df_futures.head()

Price        Close     High      Low     Open  Volume
Date
2001-01-02  1300.0  1336.75  1289.25  1331.00   92668
2001-01-03  1359.0  1367.25  1288.75  1301.00  130684
2001-01-04  1349.0  1365.50  1341.50  1360.00  110846
2001-01-05  1304.0  1380.00  1303.00  1345.75  117776
2001-01-08  1309.5  1312.50  1287.50  1308.25  120010

In [46]:
d_spot = df["Close"]
d_futures = df_futures["Close"]

In [47]:
def LogDiff(series):
    ret = 100 * np.log(series/series.shift(1))
    return ret.dropna()

data = pd.DataFrame({"ret_spot": LogDiff(d_spot), "ret_futures": LogDiff(d_features)})

In [48]:
data = data.dropna()

In [49]:
data.head()

            ret_spot  ret_futures
Date
2001-01-03  4.888407     4.438487
2001-01-04 -1.060855    -0.738556
2001-01-05 -2.659284    -3.392711
2001-01-08 -0.191965     0.420892
2001-01-09  0.380494    -0.057290

In [54]:
model = smf.ols("ret_spot ~ ret_futures", data).fit()
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:               ret_spot   R-squared:                       0.948
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                 1.168e+05
Date:                Mon, 18 May 2026   Prob (F-statistic):               0.00
Time:                        14:48:46   Log-Likelihood:                -818.40
No. Observations:                6378   AIC:                             1641.
Df Residuals:                    6376   BIC:                             1654.
Df Model:                           1
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept       0.0012      0.003      0.347      0.729      -0.006       0.008
ret_futures     0.9664      0.003    341.750      0.000       0.961       0.972
==============================================================================
Omnibus:                     2447.396   Durbin-Watson:                   2.965
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          2034830.515
Skew:                          -0.069   Prob(JB):                         0.00
Kurtosis:                      90.504   Cond. No.                         1.22
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.